FROM ubuntu:20.04
RUN apt-get update && apt-get -y install curl && apt-get install -y python3
RUN apt-get install -y python3-pip && pip3 install kafka-python && apt-get install -y vim
RUN apt -y install iputils-ping && apt -y install net-tools


COPY ./priority.json /home/priority.json
COPY ./watcher.py /home/watcher.py
COPY ./test.py /home/test.py


COPY ./test.sh /home/test.sh
RUN chmod +x /home/test.sh

# CMD ["/home/test.sh"]
